project:
  type: website
  output-dir: docs
  resources:
    - "!CLAUDE.md"

website:
  description: "A blog built with Quarto"
  site-url: https://grimmjulian.github.io
  title: "Julian Grimm"
  navbar:
    left:
      - href: index.qmd
        text: home
      # - href: blog/index.qmd
      #   text: writing
    right:
      - icon: github
        href: https://github.com/grimmjulian
      - icon: linkedin
        href: https://www.linkedin.com/in/grimmjulian225/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



